import Head from 'next/head'
import {
    Heading,
    Center,
    Flex,
    Button,
    Stack,
    HStack,
    VStack,
    Text,
    Input,
    Box,
    Image,
    Switch,
    useColorModeValue,
    useBreakpointValue,
    Container,
    useDisclosure,
    Divider
} from "@chakra-ui/react";
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import { Form, FormControl, FormErrorMessage, FormLabel } from '@chakra-ui/react'
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import { ref, uploadBytes, getDownloadURL, getStorage } from 'firebase/storage';
import { useAuth } from "../firebase";
import TopDrawer from '../constanst/components/drawer';
import UserDataContext from '../context/UserDataContext';
import HomeNav from '../constanst/components/home_nav';


export default function TermsCondition() {
    const userDataContext = useContext(UserDataContext);

    return (
        <>
            <Container maxW="window.innerWidth" p='0' color={'white'}>
                <Head>
                    <title>AEXE Application</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/aexelogo.png" />
                </Head>


                <HomeNav />
                <Flex
                    height="100vh"
                    justifyContent={'center'}
                    alignItems={'center'}>
                    <VStack spacing={7} width={'78%'}>
                        <Image
                            boxSize={'20vw'}
                            w='90vw'
                            objectFit={'contain'}
                            src={'/aexelogo.png'}>
                        </Image>
                        <Center>
                            <Heading fontSize={'5xl'} color={'#97392F'} alignSelf={'flex-start'}>AEXE App</Heading>
                        </Center>
                        <Text fontSize={'lg'} color={'black'}>AEXE is an augmented reality-based application instructor where it will helps the gym instructor and its customers to execute the exercise properly.  AEXE offers different exercises that is well-suitable for your body (BMI).
                        </Text>
                        <Text fontSize={'lg'} color={'black'}>To download the application the needed software requirement are the following:</Text>
                        <Text fontSize={'lg'} color={'black'}>Operating System:Android 7.0 Nugget to latest</Text>
                        <Text fontSize={'lg'} color={'black'}>RAM Required:8GB RAM</Text>
                        <Text fontSize={'lg'} color={'black'}>Camera Required</Text>
                    </VStack>
                </Flex>





            </Container>
        </>
    )
}