import Head from 'next/head'
import { 
  Heading, 
  Center, 
  Flex, 
  Button, 
  Stack, 
  HStack, 
  VStack, 
  Text, 
  Input, 
  Box, 
  Image, 
  Switch, 
  useColorModeValue,
  useBreakpointValue, 
  Container, 
  useDisclosure,
  Divider,
  SimpleGrid
} from "@chakra-ui/react";
import { Grid, GridItem } from '@chakra-ui/react'
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react'
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { AddIcon, SmallAddIcon } from '@chakra-ui/icons';
import { ChakraProvider } from '@chakra-ui/provider';


export default function Messages(){
  const isDesktop = useBreakpointValue({ base: false, lg: true })
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();
  useEffect(() => {
    setTimeout(() => {
      const checkSession = localStorage.getItem("email");
      if (!checkSession) {
        Router.push("/");
      }   
    }, []);
  }, []);

    return(
        <> 
      <Head>
        <title>Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>

          <Box as="section" pb={{ base: '12', md: '24' }}  bg="#2F5597" > 
            <Box as="nav" 
                bg="bg-surface" 
                boxShadow={useColorModeValue('sm', 'sm-dark')}>
              <Flex>
                <IconButton
                ref={btnRef}
                icon={<FiMenu fontSize="1.25rem"/>}
                onClick={onOpen}
                aria-label="Open Menu"
                bg="#2F5597"
                />
                <IconButton
                icon={<Image src="/aexelogo.png"/>}
                w="5px"
                isRound={true}
                aria-label="Homepage"
                onClick={() => Router.push("/dashboard")}
                />
              <Heading marginLeft={25} textColor="orange" >AEXE</Heading>

              <Drawer
                isOpen={isOpen}
                placement="left"
                colorScheme={"blue"}
                onClose={onClose}
                finalFocusRef={btnRef}>

                <DrawerOverlay/>
                <DrawerContent>
                  <DrawerCloseButton />

                  <DrawerHeader bgColor='#2F5597'>
                    <HStack>
                     
                      <Heading as='h4' size='md' color='whiteAlpha.900'>Welcome</Heading>
                    </HStack>
                  </DrawerHeader>

                  <DrawerBody bgColor='#8FAADC'>
                    <Flex flexDir="column" align="center">
                      <NextLink href="/Messages" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="Meesages" 
                        my={5} w="100%" 
                        textColor='#DAE3F3' 
                        color="blue">Messages</Button>
                      </NextLink>
                  </Flex>

                  <Flex flexDir="column" align="center">
                      <NextLink href="/ARInstructor" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="AR Instructor"
                         my={5} w="100%" 
                         textColor='#DAE3FE'>AR Instructor</Button>
                      </NextLink>
                  </Flex>

                  <Flex flexDir="column" align="center">
                      <NextLink href="/Announcement" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="Announcements" 
                        my={5} w="100%" 
                        textColor='#DAE3F3'>Announcement</Button>
                      </NextLink>
                  </Flex>

                  <Flex flexDir="column" align="center">
                      <NextLink href="/Forums" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="Forums" 
                        my={5} w="100%" 
                        textColor='#DAE3F3'>Forums</Button>
                      </NextLink>
                  </Flex>

                  <Flex flexDir="column" align="center">
                      <NextLink href="/InquiriesConcern.js" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="Inquiries and Concerns" 
                        my={5} w="100%" 
                        textColor='#DAE3F3'>Inquiries/Concern</Button>
                      </NextLink>
                  </Flex>

                  <Flex flexDir="column" align="center">
                      <NextLink href="/Settings" passHref>
                        <Button as="a" 
                        variant="ghost" 
                        aria-label="Settings" 
                        my={5} w="100%" 
                        textColor='#DAE3F3'>Settings</Button>
                      </NextLink>
                  </Flex>

                  </DrawerBody>

                  <DrawerFooter bgColor='#8FAADC'>
                    <Button colorScheme='red'
                    onClick={() => {Router.push("/")
                    localStorage.clear();
                  }}>Logout</Button>
                  </DrawerFooter>

                </DrawerContent>
              </Drawer>

              </Flex>
            </Box>

            <Center>
              <Box bg="lavender" w="1550px" h="1000px" >
                <Center>
                  <SimpleGrid marginLeft="3%" marginRight="3%" marginTop="5%" spacing={10} columns={4}>
                  <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/bmi.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>BMI</Heading>
                      <Text>BMI</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/fullbody.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Full Body</Heading>
                      <Text>Full Body </Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/lowerbody.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Lower Body</Heading>
                      <Text>Lower Body</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/legbutt.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Leg and Butt</Heading>
                      <Text>Leg and Butt</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/abs.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Abs</Heading>
                      <Text>Exercise for enhancing abs</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/chest.png"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Chest</Heading>
                      <Text>Chest</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                   <Card maxW='sm' variant='elevated' boxShadow="2xl">
                    <CardBody>
                      <Image 
                      src="/shoulderback.jpg"
                      borderRadius='lg'/>
                      <Stack mt='6' spacing='3'>
                      <Heading size='md'>Shoulder</Heading>
                      <Text>Shoulder</Text>
                      </Stack>
                    </CardBody>
                    <Divider />
                    <CardFooter>
                        <Button variant='solid' colorScheme='blue'>
                          View
                        </Button>
                    </CardFooter>
                   </Card>

                  </SimpleGrid>                 
                </Center>

          
              </Box>
            </Center>
          </Box>    
        </>
    ) 
}