import Head from 'next/head'
import { 
  Heading, 
  Center, 
  Flex, 
  Button, 
  Stack, 
  HStack, 
  VStack, 
  Text, 
  Input, 
  Box, 
  Image, 
  Switch, 
  useColorModeValue,
  useBreakpointValue, 
  Container, 
  useDisclosure, 
  FormControl
} from "@chakra-ui/react";
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from "@chakra-ui/avatar"
import React, { useEffect, useState, useContext } from "react";
import { IconButton } from '@chakra-ui/react'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";

import Sidebar from '../constanst/components/Sidebar';
import { FiMenu } from 'react-icons/fi';
import { Search2Icon } from '@chakra-ui/icons';
import NextLink from "next/link";
import Router from "next/router";



export default function Messages(){
  const btnRef = React.useRef();
  const { isOpen, onOpen, onClose } = useDisclosure();
  useEffect(() => {
    setTimeout(() => {
      const checkSession = localStorage.getItem("email");
      if (!checkSession) {
        Router.push("/");
      }      
    }, []);
  }, []);

  
  

    return(
        <> 
      <Head>
        <title>Messages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>
          
      <Box as="section" pb={{ base: '12', md: '24' }}  bg="#2F5597"> 
  <Box as="nav" bg="bg-surface" boxShadow={useColorModeValue('sm', 'sm-dark')}>
    <Flex>
      <IconButton
      ref={btnRef}
      icon={<FiMenu fontSize="1.25rem"/>}
      onClick={onOpen}
      aria-label="Open Menu"
      bg="#2F5597"
      />

      <IconButton
      icon={<Image src="/aexelogo.png"/>}
      w="5px"
      isRound={true}
      aria-label="Homepage"
      onClick={() => Router.push("/dashboard")}
      />
      <Heading marginLeft={25} textColor="orange">AEXE</Heading>

    <Drawer
      isOpen={isOpen}
      placement="left"
      colorScheme={"blue"}
      onClose={onClose}
      finalFocusRef={btnRef}>

      <DrawerOverlay/>
      <DrawerContent>
        <DrawerCloseButton />

        <DrawerHeader bgColor='#2F5597'>
          <HStack>
            <Avatar bg='teal.500' name='getInitials'></Avatar>
            <Heading as='h4' size='md' color='whiteAlpha.900'>Welcome</Heading>
          </HStack>
        </DrawerHeader>

        <DrawerBody bgColor='#8FAADC'>
          <Flex flexDir="column" align="center">
            <NextLink href="/Messages" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="Messages" 
              my={5} w="100%" 
              textColor='#DAE3F3' 
              color="blue">Messages</Button>
            </NextLink>
        </Flex>

        <Flex flexDir="column" align="center">
            <NextLink href="/ARInstructor" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="AR Instructor" 
              my={5} w="100%" 
              textColor='#DAE3FE'>AR Instructor</Button>
            </NextLink>
        </Flex>

        <Flex flexDir="column" align="center">
            <NextLink href="/Announcement" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="Announcements" 
              my={5} w="100%" 
              textColor='#DAE3F3'>Announcement</Button>
            </NextLink>
        </Flex>

        <Flex flexDir="column" align="center">
            <NextLink href="/Forums" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="Forums" 
              my={5} w="100%" 
              textColor='#DAE3F3'>Forums</Button>
            </NextLink>
        </Flex>

        <Flex flexDir="column" align="center">
            <NextLink href="/InquiriesConcern.js" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="Inquiries and Concerns" 
              my={5} w="100%" 
              textColor='#DAE3F3'>Inquiries/Concern</Button>
            </NextLink>
        </Flex>

        <Flex flexDir="column" align="center">
            <NextLink href="/Settings" passHref>
              <Button as="a" 
              variant="ghost" 
              aria-label="Settings" 
              my={5} w="100%" 
              textColor='#DAE3F3'>Settings</Button>
            </NextLink>
        </Flex>
        </DrawerBody>

        <DrawerFooter bgColor='#8FAADC'>
          <Button colorScheme='red'
          onClick={() => {Router.push("/")
          localStorage.clear();
        }}>Logout</Button>
        </DrawerFooter>

      </DrawerContent>
    </Drawer>

    </Flex>
  </Box>

            <Center>
              <Box bg="lavender" w="1550px" h="800px">
                <Flex bg="#8FAADC" w="300px" h="800px" borderEnd="1px solid"
                  borderColor="gray.200" direction="column">


              <Flex
                h="100vh">
                  <Sidebar/>
                    
                  <Flex bg="blue.100" flex={1}>

                  /</Flex>
              </Flex>
                    
                    
                  
                </Flex>



              </Box>
            </Center>
            


       </Box>

          
        </>
    ) 
}
