import Head from 'next/head'
import { 
  Heading, 
  Center, 
  Flex, 
  Button, 
  Stack, 
  HStack, 
  VStack, 
  Text, 
  Input, 
  Box, 
  Image, 
  Switch, 
  IconButton, 
  useColorModeValue,
  useBreakpointValue, 
  Container, 
  useDisclosure
} from "@chakra-ui/react";
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser} from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import { FiMenu } from 'react-icons/fi'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import NextLink from 'next/link'
import { TextareaAutosizeProps } from 'react-textarea-autosize';
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react'
import { Textarea, Divider, Header } from '@chakra-ui/react';
import Router from "next/router";
import { db, storage} from "../firebase";
import { ref, uploadBytes, getDownloadURL, getStorage } from 'firebase/storage';
import { useAuth } from "../firebase";
import { AttachmentIcon } from '@chakra-ui/icons';
import { collection, addDoc, getDocs, doc,  onSnapshot,serverTimestamp } from 'firebase/firestore';
import TopDrawer from '../constanst/components/Drawer';



export default function Dashboard() {
  const currentUser = useAuth();
  const isDesktop = useBreakpointValue({ base: false, lg: true })
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();
  const [user, setUser] = useState();

  useEffect(() => {
    setTimeout(() => {
      const checkSession = localStorage.getItem("email");
      const user_data = JSON.parse(checkSession);
      checkSession?
      setUser(user_data)
     : Router.push("/");
      
    }, []);
  }, []);

  const [ Posts, setPost] = useState([]);

 useEffect (
  () => 
    onSnapshot(collection(db,"announce"),(snapshot) =>
      setPost(snapshot.docs.map(doc => ({...doc.data(), id: doc.id})))
    ),
  []
  );

    return (
       <>

      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>
          
      <Box as="section" pb={{ base: '12', md: '24' }}  bg="#97392F" h="100vh"> 
            <TopDrawer/>


            <Center>
              <Box bg="#97392F" minH="70vh" borderRadius={'lg'} mt="5vh">
                <HStack 
                align="justify" 
                mt="3%" ml="5%" mr="5%" 
                justifyContent="center" 
                spacing="20px">

                <Card 
                size="lg" 
                align='center'
                variant="outline"
                shadow="base"
                width="25vw"
                bg="#ffffff"
                h="37vh"
                outlineColor="gray.900">

                <CardBody>
                  <Center>
                    <Avatar 
                    src={user?.profile_url}
                    size="2xl" 
                    mt="10%"
                    bg='teal.500' >
                    </Avatar>
                  </Center>
                  
                  <Stack mt='6' spacing='3' textAlign='center'>
                    <Heading size='md' textAlign="center">{user?.first_name} {user?.last_name}</Heading>
                    <Text>
                      About
                    </Text>
                    <Text>
                    ({user?.age} years old, {user?.address})
                    </Text>
                  </Stack>
                </CardBody>

                <CardFooter>
                  <Divider/>
                  
                </CardFooter>
              </Card>
              <VStack>
                      {Posts === undefined? (<>
                        </>)
                        : 
                        (Posts.map((data, index) => {
                          if(data.user?.id === user?.id) {
                          return(
                          <Card
                            key={index}
                            width="35vw"
                            direction={{ base: 'column', sm: 'row' }}
                            overflow='hidden'
                            bg="gray.100"
                            variant="outline"
                            shadow="base"
                            outlineColor="gray.900"
                            // marginTop="10vh"
                          >
                            <VStack>
                              <CardBody padding={"1em"} paddingTop={"2em"}>
                                <HStack justifyContent={"flex-start"}>
                                  <Avatar 
                                  src={data?.user?.profile_url}
                                  bg='teal.500'  
                                  size="sm" align="center" 
                                  marginTop="1"></Avatar>
                                  <Heading size='md' color={"black"}>{data?.user?.first_name} {data?.user?.last_name}</Heading>
                                </HStack>
                                <Center padding={"2em"}>
                                  <Text>{data?.newPost}</Text>
                                </Center>
                              </CardBody>
                            </VStack>
                          </Card>
                          )}}))
                        }
                  </VStack>
                </HStack>
              
                  

                  
              </Box>
            </Center>

          </Box>


          
        </>
      )
}
