import Head from 'next/head'
import {
    Heading,
    Center,
    Flex,
    Button,
    Stack,
    HStack,
    VStack,
    Text,
    Input,
    Box,
    Image,
    Switch,
    useColorModeValue,
    useBreakpointValue,
    Container,
    useDisclosure,
    Divider
} from "@chakra-ui/react";
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import { Form, FormControl, FormErrorMessage, FormLabel } from '@chakra-ui/react'
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import { ref, uploadBytes, getDownloadURL, getStorage } from 'firebase/storage';
import { useAuth } from "../firebase";
import TopDrawer from '../constanst/components/drawer';
import UserDataContext from '../context/UserDataContext';
import HomeNav from '../constanst/components/home_nav';


export default function TermsCondition() {
    const userDataContext = useContext(UserDataContext);

    return (
        <>
            <Container maxW="window.innerWidth" p='0' color={'white'}>
                <Head>
                    <title>Terms and Condition</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/aexelogo.png" />
                </Head>


                <HomeNav />
                <Flex
                    height="100vh"
                    justifyContent={'center'}
                    alignItems={'center'}>
                    <VStack spacing={7} width={'78%'}>
                        <Heading fontSize={'5xl'} color={'#97392F'} alignSelf={'flex-start'}>Terms and Condition</Heading>
                        <Text fontSize={'lg'} color={'black'}>Essentially, a Terms and Conditions agreement is a contract between your business and the user of your website or app - whether they are an individual or a business. You may see Terms and Conditions agreements referred to as Terms of Service (ToS) or Terms of Use (ToU). There's no practical difference between these terms and companies use them interchangeably.
                            Having a Terms and Conditions agreement is not a legal requirement, but having one is important as they protect your business and create a set of rules that anyone using your app or website must agree to</Text>
                        <Text fontSize={'lg'} color={'black'}>Essentially, a Terms and Conditions agreement is a contract between your business and the user of your website or app - whether they are an individual or a business. You may see Terms and Conditions agreements referred to as Terms of Service (ToS) or Terms of Use (ToU). There's no practical difference between these terms and companies use them interchangeably.
                            Having a Terms and Conditions agreement is not a legal requirement, but having one is important as they protect your business and create a set of rules that anyone using your app or website must ntract between your business and the user of your website or app - whether they are an individual.</Text>
                        <Text fontSize={'lg'} color={'black'}>Having a Terms and Conditions agreement is not a legal requirement, but having one is important as they protect your business and create a set of rules that anyone using your app or website must agree to.</Text>

                        <Divider visibility={'hidden'} />
                        <Heading fontSize={'5xl'} color={'#97392F'} alignSelf={'flex-start'}>Privacy Policy</Heading>
                        <Text fontSize={'lg'} color={'black'}>Our website application collects personal information, such as name, and email address from users for the purpose of improving customer service, providing a personalized user experience, processing payments, and sending relevant updates. We are committed to safeguarding this information and will not sell, trade, or rent it to third parties. We may share non-personal demographic information with trusted partners and comply with legal requirements. By using our application, you agree to this Privacy Policy. For any inquiries, please contact us at 09062447988 or email us at zamorafitnessdrive@gmail.com.</Text>


                    </VStack>
                </Flex>





            </Container>
        </>
    )
}