import Head from 'next/head'
import {
  Heading,
  Center,
  Flex,
  Button,
  Stack,
  HStack,
  VStack,
  Text,
  Input,
  Box,
  Image,
  Switch,
  useColorModeValue,
  useBreakpointValue,
  Container,
  useDisclosure,
  SimpleGrid,
  Icon
} from "@chakra-ui/react";
import { Grid, GridItem } from '@chakra-ui/react'
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react'
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { Divider } from '@chakra-ui/react'
import { AddIcon, ChevronLeftIcon, SmallAddIcon, StackDivider, textTransform } from '@chakra-ui/icons';
import { ChakraProvider } from '@chakra-ui/provider';
import TopDrawer from '../../constanst/components/drawer';


export default function fullbody() {
  const isDesktop = useBreakpointValue({ base: false, lg: true })
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();

  return (
    <>
      <Head>
        <title>Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>

      <Box as="section" pb={{ base: '12', md: '24' }} bg="#97392F" >
        <TopDrawer />
        <Center>
          <Box bgColor="#ffffff" w="1550%" h="1020%" >
            <HStack direction="row" align="flex-end">
              <IconButton mt="2%" ml="3%" as={ChevronLeftIcon} size="sm"
                bgColor="#ffffff"
                onClick={() => Router.push("/exercise")} />

            </HStack>

            <Container maxW='container.md'>
              <Image
                src="/legbutt.jpg"
                borderRadius='lg' />
              <Card variant='elevated' mb="10%">
                <CardHeader>
                  <Heading>Leg and Butt Exercises</Heading>
                  <Text size='sm' marginTop={2} spacing={2} textAlign="justify" lineHeight={6}>
                    Leg exercises work all of the major muscular groups in your body,
                    which promotes healthy movement patterns in daily life and enhances
                    overall athletic performance. Having a powerful lower body will also
                    help you stay healthy and manage long-term problems like diabetes,
                    heart disease, and arthritis.
                  </Text>
                </CardHeader>
                <CardBody>
                  <Stack spacing='4'>
                    <Box>
                      <Heading size='sm' >Exercises:</Heading>
                    </Box>


                    <Box>
                      <Text>Alternative side lunge</Text>
                      <Text>Ankle hops</Text>
                      <Text>Booty squeeze</Text>
                      <Text>Bridge and twist</Text>
                      <Text>Burpees</Text>
                      <Text>Clam shell</Text>
                      <Text>Double pulse squat jump</Text>
                      <Text>Humstring curl</Text>
                      <Text>Jump squat</Text>
                      <Text>Lunge back kicks</Text>
                      <Text>Single leg bridge</Text>
                      <Text>Squat thrust</Text>

                    </Box>
                  </Stack>
                </CardBody>
              </Card>

            </Container>



          </Box>
        </Center>

      </Box>
    </>
  )
}
