import Head from 'next/head'
import {
  Heading,
  Center,
  Flex,
  Button,
  Stack,
  HStack,
  VStack,
  Text,
  Input,
  Box,
  Image,
  Switch,
  useColorModeValue,
  useBreakpointValue,
  Container,
  useDisclosure,
  SimpleGrid,
  Icon
} from "@chakra-ui/react";
import { Grid, GridItem } from '@chakra-ui/react'
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react'
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { Divider } from '@chakra-ui/react'
import { AddIcon, ChevronLeftIcon, SmallAddIcon, StackDivider, textTransform } from '@chakra-ui/icons';
import { ChakraProvider } from '@chakra-ui/provider';
import TopDrawer from '../../constanst/components/drawer';


export default function fullbody() {
  const isDesktop = useBreakpointValue({ base: false, lg: true })
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();

  return (
    <>
      <Head>
        <title>Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>

      <Box as="section" pb={{ base: '12', md: '24' }} bg="#97392F" >
        <TopDrawer />
        <Center>
          <Box bgColor="#ffffff" w="1550%" h="1020%" >
            <HStack direction="row" align="flex-end">
              <IconButton mt="2%" ml="3%" as={ChevronLeftIcon} size="sm"
                bgColor="#ffffff"
                onClick={() => Router.push("/exercise")} />

            </HStack>

            <Container maxW='container.md'>
              <Image
                src="/lowerbody.jpg"
                borderRadius='lg' />
              <Card variant='elevated' mb="10%">
                <CardHeader>
                  <Heading>Lower body Exercises</Heading>
                  <Text size='sm' marginTop={2} spacing={2} textAlign="justify" lineHeight={6}>
                    Lower-body workouts are meant to strengthen the legs,
                    glutes, lower back, and hips. Exercises for the lower
                    body include lunges, squats, deadlifts, and others.
                    Building foundational strength for everyday actions
                    through lower body exercise. Leg exercises balance out
                    your training program by assisting in the development
                    of muscle, stability, and quickness in your lower body.
                  </Text>
                </CardHeader>
                <CardBody>
                  <Stack spacing='4'>
                    <Box>
                      <Heading size='sm' >Exercises:</Heading>
                    </Box>


                    <Box>
                      <Text>Butt kicks</Text>
                      <Text>Forward leg swing</Text>
                      <Text>High kicks</Text>
                      <Text>High knees</Text>
                      <Text>Jumping jacks</Text>
                      <Text>Lateral leg swing</Text>
                      <Text>Lunge twist</Text>
                      <Text>Mountain climbers</Text>
                      <Text>Run in place</Text>
                      <Text>Squat side kick</Text>

                    </Box>
                  </Stack>
                </CardBody>
              </Card>

            </Container>



          </Box>
        </Center>

      </Box>
    </>
  )
}
