import Head from 'next/head'
import {
  Heading,
  Center,
  Flex,
  Button,
  Stack,
  HStack,
  VStack,
  Text,
  Input,
  Box,
  Image,
  Switch,
  useColorModeValue,
  useBreakpointValue,
  Container,
  useDisclosure,
  SimpleGrid,
  Icon
} from "@chakra-ui/react";
import { Grid, GridItem } from '@chakra-ui/react'
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react'
import { Avatar, AvatarBadge, AvatarGroup, AiOutlineUser } from '@chakra-ui/react'
import React, { useEffect, useState, useContext } from "react";
import Router from "next/router";
import { FiMenu } from 'react-icons/fi'
import { IconButton, ButtonGroup } from '@chakra-ui/react'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { Divider } from '@chakra-ui/react'
import { AddIcon, ChevronLeftIcon, SmallAddIcon, StackDivider, textTransform } from '@chakra-ui/icons';
import { ChakraProvider } from '@chakra-ui/provider';
import TopDrawer from '../../constanst/components/drawer';


export default function fullbody() {
  const isDesktop = useBreakpointValue({ base: false, lg: true })
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();

  return (
    <>
      <Head>
        <title>Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aexelogo.png" />
      </Head>

      <Box as="section" pb={{ base: '12', md: '24' }} bg="#97392F" >
        <TopDrawer />

        <Center>
          <Box bgColor="#ffffff" w="1550%" h="1020%" >
            <HStack direction="row" align="flex-end">
              <IconButton mt="2%" ml="3%" as={ChevronLeftIcon} size="sm"
                bgColor="#ffffff"
                onClick={() => Router.push("/exercise")} />

            </HStack>

            <Container maxW='container.md'>
              <Image
                src="/shoulderback.jpg"
                borderRadius='lg' />
              <Card variant='elevated' mb="10%">
                <CardHeader>
                  <Heading>Shoulder and Back Exercises</Heading>
                  <Text size='sm' marginTop={2} spacing={2} textAlign="justify" lineHeight={6}>
                    A shoulder and back training regimen is intended to develop broad,
                    enormous shoulder muscles and a muscular, powerful back.
                    The advantages of working your shoulders and back at the same time,
                    as well as a general description of the workout. When a program is
                    correctly designed, training the shoulders and back can increase
                    strength and bulk.
                  </Text>
                </CardHeader>
                <CardBody>
                  <Stack spacing='4'>
                    <Box>
                      <Heading size='sm' >Exercises:</Heading>
                    </Box>


                    <Box>
                      <Text>Alternating superman</Text>
                      <Text>Anklet push ups</Text>
                      <Text>Arm cross side lunge</Text>
                      <Text>Arm swings</Text>
                      <Text>Bear walks</Text>
                      <Text>Break dancer kick</Text>
                      <Text>Crab toe touches</Text>
                      <Text>Half squat jab cross</Text>
                      <Text>Lower back stretch</Text>
                      <Text>Neck rolls</Text>
                      <Text>Pilates swimming</Text>
                      <Text>Shoulder stretch</Text>

                    </Box>
                  </Stack>
                </CardBody>
              </Card>

            </Container>



          </Box>
        </Center>

      </Box>
    </>
  )
}
